[build]
  command = "hugo --gc --minify"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.121.1" # Change to your Hugo version
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
